version: '3.7'

volumes:
  data:

services:
  mysql:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro
      - ./conf.d:/etc/mysql/conf.d:ro
